<!DOCTYPE h1 PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=gbk" />
</head>
<h1>增加过滤IP</h1>
<form method="post" action="/filter/addfilter">
	<table>
			<td>过滤IP：</td>
			<td><input type="text" name="ip"></td>
		</tr>
		<tr>
			<td><input type="submit" value="提交"></td>
			<td><input type="reset" value="重新填写"></td>
		</tr>
	</table>
</form>