<!DOCTYPE h1 PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=gbk" />
</head>
<h1>增加投票选项</h1>
<form method="post" action="/vote/additem">
	<table>
		<tr>
			<td>选项名称：</td>
			<td><input type="text" name="name"></td>
		</tr>
		<tr>
			<td>描述：</td>
			<td><textarea rows="5" cols="50" name="description"></textarea></td>
		</tr>
		<tr>
			<td>初始化投票数：</td>
			<td><input type="text" name="vote_count"></td>
		</tr>
		<tr>
			<td><input type="submit" value="提交"></td>
			<td><input type="reset" value="重新填写"></td>
		</tr>
	</table>
</form>